"""base de conhecimento (Cerebro)

Duas tabelas: `knowledge_document` (proveniencia — um arquivo do corpus, sua
autoridade e sua licenca) e `knowledge_chunk` (texto recuperavel, cada trecho
guardando a pagina de onde veio). A separacao existe porque um documento pode
ser catalogado sem ser indexado: um livro cuja licenca proibe redistribuicao
continua sendo uma fonte legitima a registrar.

O autogenerate tambem detectou uma mudanca de indice em `subscription`
(unique=False -> True), vinda de trabalho de cobranca ainda nao commitado.
Removida daqui de proposito: nao e desta migration, e leva-la junto faria a
cobranca migrar por carona numa revisao que nao fala dela.

Revision ID: 84eee98176f8
Revises: d03e79073756
Create Date: 2026-08-20 11:27:30.690738
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84eee98176f8'
down_revision: Union[str, None] = 'd03e79073756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.Enum('LIVRO', 'SLIDE', 'ARTIGO', 'FICHA', 'EXERCICIO', 'NORMA', 'VIDEO', 'LINK', 'OUTRO', name='documentkind', native_enum=False, length=12), nullable=False),
    sa.Column('authority', sa.Enum('OFICIAL', 'CIENTIFICA', 'TECNICA', 'SECUNDARIA', 'NAO_VERIFICADA', name='sourceauthority', native_enum=False, length=16), nullable=False),
    sa.Column('author', sa.String(length=300), nullable=True),
    sa.Column('reference', sa.String(length=1000), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('licence_note', sa.String(length=500), nullable=True),
    sa.Column('is_versioned', sa.Boolean(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'EXTRAIDO', 'FALHOU', 'IGNORADO', name='ingeststatus', native_enum=False, length=10), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('knowledge_chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('heading', sa.String(length=300), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'ordinal', name='uq_knowledge_chunk_position')
    )
    with op.batch_alter_table('knowledge_chunk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_chunk_document_id'), ['document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_chunk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_chunk_document_id'))

    op.drop_table('knowledge_chunk')
    op.drop_table('knowledge_document')
    # ### end Alembic commands ###
