"""selection studies and performance indices

Revision ID: 983b5bc9bf8f
Revises: cb579fc58c75
Create Date: 2026-07-24 11:41:45.088844
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '983b5bc9bf8f'
down_revision: Union[str, None] = 'cb579fc58c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('expression', sa.String(length=500), nullable=False),
    sa.Column('goal', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('selection_study',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('function_text', sa.String(length=1000), nullable=True),
    sa.Column('objective_text', sa.String(length=1000), nullable=True),
    sa.Column('free_variables', sa.JSON(), nullable=False),
    sa.Column('combinator', sa.String(length=3), nullable=False),
    sa.Column('index_name', sa.String(length=160), nullable=True),
    sa.Column('index_expression', sa.String(length=500), nullable=True),
    sa.Column('index_goal', sa.String(length=10), nullable=True),
    sa.Column('normalization', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ranking_criterion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['selection_study.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('selection_constraint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('operator', sa.String(length=20), nullable=False),
    sa.Column('property_slug', sa.String(length=160), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('value_min', sa.Float(), nullable=True),
    sa.Column('value_max', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=60), nullable=True),
    sa.Column('class_slugs', sa.JSON(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['selection_study.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('selection_constraint')
    op.drop_table('ranking_criterion')
    op.drop_table('selection_study')
    op.drop_table('performance_index')
    # ### end Alembic commands ###
