"""saved_chart

Revision ID: c557d5207240
Revises: f6482f1969e3
Create Date: 2026-08-31 11:41:27.181258
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c557d5207240'
down_revision: Union[str, None] = 'f6482f1969e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_chart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_chart', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_chart_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_chart', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_chart_project_id'))

    op.drop_table('saved_chart')
    # ### end Alembic commands ###
