"""import jobs and templates

Revision ID: cb579fc58c75
Revises: f1f8bb68cba1
Create Date: 2026-07-22 16:11:32.665286
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb579fc58c75'
down_revision: Union[str, None] = 'f1f8bb68cba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('file_format', sa.String(length=10), nullable=False),
    sa.Column('sheet_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'VALIDADO', 'IMPORTADO', 'CANCELADO', 'REVERTIDO', name='importstatus', native_enum=False, length=12), nullable=False),
    sa.Column('mapping', sa.JSON(), nullable=True),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('valid_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_mapping_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('mapping', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_job_id', sa.Integer(), nullable=True))
        # SQLite batch mode requires named constraints.
        batch_op.create_foreign_key(
            'fk_material_import_job_id', 'import_job', ['import_job_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_constraint('fk_material_import_job_id', type_='foreignkey')
        batch_op.drop_column('import_job_id')

    op.drop_table('import_mapping_template')
    op.drop_table('import_job')
    # ### end Alembic commands ###
