"""material_keyword

Revision ID: d63a586a1564
Revises: c557d5207240
Create Date: 2026-08-31 17:10:59.557783
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd63a586a1564'
down_revision: Union[str, None] = 'c557d5207240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_keyword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_keyword', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_keyword_keyword'), ['keyword'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_keyword_material_id'), ['material_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_keyword', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_keyword_material_id'))
        batch_op.drop_index(batch_op.f('ix_material_keyword_keyword'))

    op.drop_table('material_keyword')
    # ### end Alembic commands ###
