"""initial schema

Revision ID: f1f8bb68cba1
Revises: 
Create Date: 2026-07-22 14:14:26.430684
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f8bb68cba1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['material_class.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('property_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.Enum('FISICA', 'MECANICA', 'TERMICA', 'ELETRICA', 'AMBIENTAL', 'ECONOMICA', name='propertycategory', native_enum=False, length=20), nullable=False),
    sa.Column('physical_dimension', sa.String(length=120), nullable=False),
    sa.Column('canonical_unit', sa.String(length=60), nullable=False),
    sa.Column('accepted_units', sa.JSON(), nullable=False),
    sa.Column('is_interval', sa.Boolean(), nullable=False),
    sa.Column('better_direction', sa.Enum('HIGHER', 'LOWER', 'NEUTRAL', name='betterdirection', native_enum=False, length=10), nullable=False),
    sa.Column('allows_log_scale', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('reference', sa.String(length=1000), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subclass', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['material_class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_name'), ['name'], unique=False)

    op.create_table('material_property_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('value_scalar', sa.Float(), nullable=True),
    sa.Column('value_min', sa.Float(), nullable=True),
    sa.Column('value_max', sa.Float(), nullable=True),
    sa.Column('value_typical', sa.Float(), nullable=True),
    sa.Column('original_unit', sa.String(length=60), nullable=True),
    sa.Column('normalized_value', sa.Float(), nullable=True),
    sa.Column('canonical_unit', sa.String(length=60), nullable=True),
    sa.Column('conversion_method', sa.String(length=120), nullable=True),
    sa.Column('uncertainty', sa.Float(), nullable=True),
    sa.Column('measurement_condition', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('data_quality', sa.Enum('MEDIDO', 'IMPORTADO', 'ESTIMADO', name='dataquality', native_enum=False, length=12), nullable=False),
    sa.Column('is_missing', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['property_definition.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material_property_value')
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_name'))

    op.drop_table('material')
    op.drop_table('source')
    op.drop_table('property_definition')
    op.drop_table('material_class')
    # ### end Alembic commands ###
