"""selection_study_method

Adds ``SelectionStudy.method`` (M5): which ranking method
(``weighted_sum``/``topsis``/``promethee``) a saved study re-runs with, so it
stays reproducible without the caller having to guess the method that was
active when it was saved. ``server_default='weighted_sum'`` — same reasoning
as ``fc5a731dd162``'s ``contains_third_party_data``: the column is NOT NULL
on a table that can already hold rows (any study saved before this
migration), so existing rows need a real value written by the database
itself, not just the ORM-side ``default=`` on the model, which only applies
to rows inserted from here on.

Revision ID: f8c93a1d8844
Revises: d63a586a1564
Create Date: 2026-09-01 06:45:30.012166
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c93a1d8844'
down_revision: Union[str, None] = 'd63a586a1564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selection_study', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'method',
                sa.String(length=20),
                nullable=False,
                server_default='weighted_sum',
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selection_study', schema=None) as batch_op:
        batch_op.drop_column('method')

    # ### end Alembic commands ###
