"""indices nas chaves estrangeiras

Até aqui o schema tinha exatamente um índice não-único — ``material.name`` — e
nenhuma chave estrangeira indexada. São seis, e todas aparecem em junção ou em
filtro de tela: a classe de um material (todo gráfico colorido por classe), a
propriedade de um valor (a distribuição do painel), o job que criou um material
(o rollback da importação), a fonte de um valor, e as duas que penduram
restrições e critérios num estudo.

O ganho foi medido, não presumido, sobre um catálogo sintético de 5 000
materiais e 60 000 valores — mil vezes o banco de desenvolvimento atual:

* ``GET /dashboard/distribution``: 43,0 ms -> 33,4 ms (-22%)
* materiais de uma classe: 0,83 ms -> 0,54 ms (-35%)
* ``GET /dashboard/overview``: sem mudança (183 ms), e nem poderia haver — são
  três junções **agregadas sobre o catálogo inteiro**, e um índice não abrevia
  uma varredura que precisa ler tudo. O perfil mostra 7 consultas e nenhum N+1;
  o custo é do banco, não do serviço.
* crescimento do arquivo: +10%.

Índices de cobertura mais largos foram medidos e **recusados**: compraram 13% no
overview por +33% de tamanho, e pioraram a distribuição.

**Não rode ``ANALYZE`` atrás desta migration.** Foi medido: com as estatísticas
disponíveis o planejador do SQLite passa a escolher um plano indexado para o
agregado do overview e ele fica **85% mais lento** (183 ms -> 411 ms). O acesso
por índice é aleatório; a varredura sequencial é o plano certo para agregar o
catálogo todo.

``material_property_value.material_id`` ficou de fora de propósito: é a primeira
coluna de ``uq_material_property_value_pair``, e esse índice já atende qualquer
busca por material. ``property_id``, sendo a segunda, não é alcançável por ele —
por isso ganha o seu.

Revision ID: fa369b7bbbde
Revises: 07b420ca5122
Create Date: 2026-08-12 16:02:55.425708
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fa369b7bbbde"
down_revision: Union[str, None] = "07b420ca5122"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("material", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_material_class_id"), ["class_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_material_import_job_id"), ["import_job_id"], unique=False
        )

    with op.batch_alter_table("material_property_value", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_material_property_value_property_id"), ["property_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_material_property_value_source_id"), ["source_id"], unique=False
        )

    with op.batch_alter_table("ranking_criterion", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ranking_criterion_study_id"), ["study_id"], unique=False
        )

    with op.batch_alter_table("selection_constraint", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_selection_constraint_study_id"), ["study_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("selection_constraint", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_selection_constraint_study_id"))

    with op.batch_alter_table("ranking_criterion", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ranking_criterion_study_id"))

    with op.batch_alter_table("material_property_value", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_material_property_value_source_id"))
        batch_op.drop_index(batch_op.f("ix_material_property_value_property_id"))

    with op.batch_alter_table("material", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_material_import_job_id"))
        batch_op.drop_index(batch_op.f("ix_material_class_id"))

    # ### end Alembic commands ###
